version: '3.8'
services:
  refair:
    build: .
    volumes:
      - .:/app
      - ./Dataset:/app/Dataset
    ports:
      - "8888:8888"
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
    command: ["python", "Embeddings.py"]  # First use the default command from Dockerfile

# If you specifically want to run Jupyter, you can comment out the above command and use:
    # command: ["jupyter", "notebook", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root"]